Fix the 'Content-Type' headers sent with a request.
ktonon/elm-aws-core pull request #4
Opened 2017-12-02 12:49 UTC by billstclair

Only add a `Content-Type` to a request if the user hasn't overridden it and it's not in the `Body` (in which case, the Elm `Http` module adds another `Content-Type` header taken from there).

`elm-s3` needs this, since the `Content-Type` sent with a `PUT` request is stored with the object and returned when the object is read, either via the S3 interface, which discards headers, or via a standard `HTTP GET` to the public URL.

It might be nice to have some way to return the headers on an `S3 GET` request, but for publicly-readable objects, you can get those with an `HTTP HEAD` to the public URL, so it's not vital.

2017-12-02 20:52 UTC, ktonon commented on CONTRIBUTING.md
> +elm-test
I would prefer

```shell
npm install -g elm-doc-test@4.0.0 elm-test@0.18.10
elm-make --docs=docs.json && elm-doc-test && elm-test
```

2017-12-02 20:54 UTC, ktonon commented on src/AWS/Core/Body.elm
> +
```elm
Json _ ->
    Just "application/json"
```

2017-12-02 20:56 UTC, ktonon commented on src/AWS/Core/Signers/V4.elm
> +            headers service date req.body (Debug.log "req.headers" req.headers)
Forgot to remove this?

2017-12-02 20:59 UTC, ktonon commented on src/AWS/Core/Http.elm
> +setResponseParser : Maybe (Http.Response String -> Result String a) -> Request a -> Request a
Given that the default is `Nothing` do we need to provide the option to set this to `Nothing`?

I think `(Http.Response String -> Result String a) -> Request a -> Request a` would work and make the call more readable.

2017-12-02 21:00 UTC, billstclair commented
I'm fixing these as I read them. Please let me know when you're done, and I'll commit my fixes.

2017-12-02 21:00 UTC, ktonon requested changes
Looks good. Just make the changes in the comments

2017-12-02 21:00 UTC, ktonon commented
No other comments. Thanks :)

2017-12-02 21:02 UTC, billstclair commented on src/AWS/Core/Http.elm
> +setResponseParser : Maybe (Http.Response String -> Result String a) -> Request a -> Request a
I considered that, but waffled because it doesn't let you UNSET the parser, but I think you're right that it's clearer to not put the Maybe around the arg, and add a Just inside the body.

2017-12-02 21:03 UTC, billstclair commented on src/AWS/Core/Http.elm
> +setResponseParser : Maybe (Http.Response String -> Result String a) -> Request a -> Request a
BTW, I've been rewriting the S3 code using setResponseParser, and it's much simpler than handling the expected JSON parsing error. Probably faster, too.

2017-12-02 21:07 UTC, billstclair commented on src/AWS/Core/Body.elm
> +
`mimetype` returning `Nothing` is how `V4.headers` decides to use `Service.jsonContentType service`. I'm renaming the function to `explicitMimetype` to clarify that it isn't a general purpose mimetype function.

2017-12-02 22:16 UTC, billstclair commented
I don't know the process here. I think I'm waiting on you to dismiss your review, after checking that I actually fixed your issues. I'm happy to merge, bump the version, and republish, once I get your go-ahead (since you very kindly gave me permission to commit to this repository).

If you would like permission to push to billstclair/elm-s3, just ask.

2017-12-03 00:17 UTC, ktonon approved these changes

2017-12-03 00:18 UTC, ktonon commented
Yeah, you can go ahead and bump the version. I'm not sure if you'll be able to publish. You can try, let me know if that doesn't work.

2017-12-03 00:18 UTC, merged

2017-12-03 00:57 UTC, ktonon commented
@billstclair just published as 1.1.0

Thanks for your work on this

2017-12-03 02:31 UTC, billstclair commented
My pleasure. I was worried when I decide to build an S3 client library about doing all the crypto. I was SO pleased to discover that you'd already done nearly everything. I may get elm-s3 published before I crash tonite. We'll see.

2017-12-03 04:16 UTC, billstclair commented
http://package.elm-lang.org/packages/billstclair/elm-s3/latest